export const FETCH_WALLETS_START = 'FETCH_WALLETS_START'
export const FETCH_WALLETS_SUCCESS = 'FETCH_WALLETS_SUCCESS'
export const FETCH_WALLETS_FAILED = 'FETCH_WALLETS_FAILED'

export const ADD_WALLET_START = 'ADD_WALLET_START'
export const ADD_WALLET_SUCCESS = 'ADD_WALLET_SUCCESS'
export const ADD_WALLET_FAILED = 'ADD_WALLET_FAILED'

export const CHANGE_FUNDS_START = 'CHANGE_FUNDS_START'
export const CHANGE_FUNDS_SUCCESS = 'CHANGE_FUNDS_SUCCESS'
export const CHANGE_FUNDS_FAILED = 'CHANGE_FUNDS_FAILED'

export const FETCH_TRANSACTION_START = 'FETCH_TRANSACTION_START'
export const FETCH_TRANSACTION_SUCCESS = 'FETCH_TRANSACTION_SUCCESS'
export const FETCH_TRANSACTION_FAILED = 'FETCH_TRANSACTION_FAILED'

export const ADD_TRANSACTION_START = 'ADD_TRANSACTION_START'
export const ADD_TRANSACTION_SUCCESS = 'ADD_TRANSACTION_SUCCESS'
export const ADD_TRANSACTION_FAILED = 'ADD_TRANSACTION_FAILED'

export const DELETE_TOAST = 'DELETE_TOAST'
